#- name: Set Name Prompt
#  ansible.builtin.shell: set-prompt grafana
#
#- name: Copy Grafana repo file
#  ansible.builtin.template:
#    src: grafana.repo
#    dest: /etc/yum.repos.d/grafana.repo
#
#- name: Install Grafana
#  ansible.builtin.dnf:
#    name: grafana
#    state: installed

- name: Copy Datasource
  ansible.builtin.template:
    src: prom-datasource.yml
    dest: /etc/grafana/provisioning/datasources/prom-datasource.yml

- name: Copy template
  ansible.builtin.template:
    src: sample-dash.json
    dest: /tmp/sample-dash.json

- name: Import Grafana dashboard foo
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_user: "admin"
    grafana_password: "Akhil098765@"
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: /tmp/sample-dash.json

- name: Start Grafana
  ansible.builtin.systemd_service:
    name: grafana-server
