format_version: 10
pipelines:
  ci-server:
    group: Tools
    materials:
      git-8c92c05:
        git: https://github.com/devops-i1/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:SwJnjN2xu5okR7QrKc6/6Q==:8fYPWT/nNBNEjm0So1OXTL9nXRM/dfSTdyGgTzj9pII=
    stages:
      - Ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: {command: ansible-playbook, arguments: [  "-i", "ci-server-internal.akhilsaidevops.online,", "tools.yml", "-e", "tool_name=ci-server", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321", "-e", "vault_token=${vault_token}"], run_if: passed}