format_version: 10
pipelines:
  jenkins:
    group: Tools
    materials:
      git-8c92c05:
        git: https://github.com/devops-i1/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: {command: ansible-playbook, arguments: [  "-i", "jenkins-internal.akhilsaidevops.online,", "tools.yml", "-e", "tool_name=jenkins", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ], run_if: passed}